# render.yaml
services:
  - type: web
    name: django-api
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

databases:
  - name: postgres
    plan: free