# Generated by Django 5.1.6 on 2025-08-12 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rideevent',
            name='ride_event_today_idx',
        ),
        migrations.AddIndex(
            model_name='rideevent',
            index=models.Index(condition=models.Q(('created_at__gte', datetime.datetime(2025, 8, 11, 18, 11, 45, 115769, tzinfo=datetime.timezone.utc))), fields=['id_ride', 'created_at'], name='ride_event_today_idx'),
        ),
    ]
